Import Library

In [7]:
import numpy as np

Create Numpy Arrays Using Lists 

In [8]:
my_list = [1,2,3,4,5]
numpy_array = np.array(my_list)
print("Simple NumPy Array:", numpy_array)

Simple NumPy Array: [1 2 3 4 5]


Initialize a Python NumPy Array Using Special Functions

In [9]:
zeros_array = np.zeros((2,3))
ones_array = np.ones((3,3))
constant_array = np.full((2,2),7)
range_array = np.arange(0,10,2) # Start, Stop, Step
linspace_array = np.linspace(0,1,5) # Start, Stop, num

print(f"Zeros Array:\n {zeros_array}")
print(f"Ones Array:\n {ones_array}")
print(f"Constant Array:\n {constant_array}")
print(f"Range Array:\n {range_array}")
print(f"Linspace Array:\n {linspace_array}")

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array:
 [[7 7]
 [7 7]]
Range Array:
 [0 2 4 6 8]
Linspace Array:
 [0.   0.25 0.5  0.75 1.  ]


Create Python Numpy Arrays Using Random Number Generation

In [14]:
random_array = np.random.rand(2,3)
normal_array = np.random.randn(2,2)
randint_array = np.random.randint(1,10,size=(2,3))

print(random_array)
print(normal_array)
print(randint_array)

[[0.35881041 0.65742949 0.87574092]
 [0.29081419 0.98862744 0.74529033]]
[[ 1.42193842 -0.24966204]
 [ 0.1079994  -0.5745729 ]]
[[6 2 3]
 [8 9 7]]


Create Python Numpy Arrays Using Matrix Creation Routines

In [18]:
identity_matrix = np.eye(3)
diagonal_array = np.diag([1,2,3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print(identity_matrix,'\n')
print(diagonal_array,'\n')
print(zeros_like_array,'\n')
print(ones_like_array,'\n')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

