Accessing Elements in 1D Arrays

In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr[0]) # index 0

10


Accessing Elements in Multidimensional Arrays

In [4]:
matrix1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix1[1,2]) # Baris index 1, colom index 2

6


In [7]:
cube = np.array([
    [[1,2,3],
     [4,5,6],
     [7,8,9]],

    [[10,11,12],
     [13,14,15],
     [16,17,18]]
])

print(cube[1,2,0]) # Matrix index 1, baris index 2, colom index 0

16


Slicing Arrays

In [9]:
arr = np.array([0,1,2,3,4,5])

print(arr[1:4]) # Mengambil dari index 1 sampai index 3

[1 2 3]


In [10]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


Boolean Indexing

In [11]:
arr = np.array([10,15,20,25,30])

print(arr[arr > 20])

[25 30]


In [12]:
arr = np.array([10,15,20,25,30])

print(arr[(arr > 10) & (arr < 30)])

[15 20 25]


Fancy Indexing

In [13]:
arr = np.array([10,20,30,40,50])

indices = [0,2,4]

print(arr[indices])

[10 30 50]


Integer Array Indexing

In [14]:
arr = np.array([1,2,3,4,5])

print(arr[[0,2,4]])

[1 3 5]


Ellipsis (...) in Indexing

In [15]:
cube = np.random.rand(4,4,4)

print(cube[..., 0])

[[0.14550623 0.00962706 0.11991541 0.03510114]
 [0.79062855 0.0985805  0.26447315 0.36806454]
 [0.54562283 0.2220748  0.12605028 0.95230108]
 [0.32065325 0.2117681  0.02160577 0.7115248 ]]


Using np.newaxis to Add New Dimensions

In [17]:
arr = np.array([1,2,3])

print(arr[:, np.newaxis])

[[1]
 [2]
 [3]]


Modifying Array Elements

In [18]:
arr = np.array([1,2,3,4])

arr[1:3] = 99

print(arr)

[ 1 99 99  4]
