In [1]:
import numpy as np

a = np.array([1,2,3,4,5,6])
r = a.reshape(2,3)

print(r)

[[1 2 3]
 [4 5 6]]


In [2]:
a = np.array([1,2,3,4,5,6,7,8])
r = a.reshape(2,2,2)

print(r)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
r = a.reshape(3,-1)

print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
arr = np.array([1,2,3,4,5,6])
arr.resize((3,4))

print(arr)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [5]:
arr = np.array([10,20,30,40,50])
arr.resize((2,2))

print(arr)

[[10 20]
 [30 40]]
