In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

res = np.stack((a,b),axis=0)

print(res)

[[1 2 3]
 [4 5 6]]


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.stack((a,b), axis=0))
print(np.stack((a,b), axis=1))
print(np.stack((a,b), axis=-1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [5]:
x = np.array([
    [1,2,3],
    [4,5,6] 
])

y = np.array([
    [7,8,9],
    [10,11,12]
])

print(np.stack((x,y),axis=0))
print(np.stack((x,y),axis=1))
print(np.stack((x,y),axis=2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [6]:
m = np.array([
    [[1,2],
     [3,4]],

    [[5,6],
     [7,8]]
])

n = np.array([
    [[10,20],
     [30,40]],

    [[50,60],
     [70,80]]
])

print(np.stack((m,n), axis=0))
print(np.stack((m,n), axis=1))
print(np.stack((m,n), axis=2))
print(np.stack((m,n), axis=3))

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [ 3  4]]

  [[10 20]
   [30 40]]]


 [[[ 5  6]
   [ 7  8]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [10 20]]

  [[ 3  4]
   [30 40]]]


 [[[ 5  6]
   [50 60]]

  [[ 7  8]
   [70 80]]]]
[[[[ 1 10]
   [ 2 20]]

  [[ 3 30]
   [ 4 40]]]


 [[[ 5 50]
   [ 6 60]]

  [[ 7 70]
   [ 8 80]]]]


numpy.split()

In [7]:
arr = np.arange(6)
res = np.split(arr,2)
print(res)

[array([0, 1, 2]), array([3, 4, 5])]


numpy.array_split()

In [8]:
arr = np.arange(13)
res = np.array_split(arr,4)

print(res)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


numpy.vsplit()

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
res = np.vsplit(arr,2)

print(res)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


numpy.hsplit()

In [10]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
res = np.hsplit(arr,2)

print(res)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


numpy.dsplit()

In [11]:
arr = np.arange(24).reshape((2,3,4))
res = np.dsplit(arr,2)

print(res)

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]
