Broadcasting a Scalar to a 1D Array

In [1]:
import numpy as np

arr = np.array([1,2,3])
res = arr + 1

print(res)

[2 3 4]


Broadcasting a 1D Array to a 2D Array

In [2]:
a = np.array([2,4,6])
b = np.array([[1,3,5], [7,9,11]])

res = a + b

print(res)

[[ 3  7 11]
 [ 9 13 17]]


Broadcasting in Conditional Operations

In [3]:
a = np.array([12,24,35,45,60,72])
b = np.array(["Adult", "Minor"])

res = np.where(a > 18, b[0], b[1])

print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


Using Broadcasting for Matrix Multiplication

In [4]:
m = np.array([[1,2],[3,4]])
v = np.array([10,20])

res = m * v

print(res)

[[10 40]
 [30 80]]


Scaling Data with Broadcasting

In [5]:
fd = np.array([
    [0.8, 2.9, 3.9],
    [52.4, 23.6, 36.5],
    [55.2, 31.7, 23.9],
    [14.4, 11.0, 4.9]
])

cpg = np.array([3,3,8])

res = fd * cpg

print(res)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


Adjusting Temperature Data Across Multiple Locations

In [6]:
temp = np.array([ [30, 32, 34, 33, 31],
                  [25, 27, 29, 28, 26],
                  [20, 22, 24, 23, 21] ])

corr = np.array([1.5,-0.5,2.0])
res = temp + corr[:, None]

print(res)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


Normalizing Image Data

In [7]:
img = np.array([
    [100,120,130],
    [90,110,140],
    [80,100,120]
])

m = img.mean(axis=0)
s = img.std(axis=0)

res = (img - m) / s

print(res)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


Centering Data in Machine Learning

In [8]:
data = np.array([
    [10,20],
    [15,25],
    [20,30]
])

m = data.mean(axis=0)
res = data - m

print(res)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
