In [1]:
import numpy as np

Addtion of Arrays

In [2]:
a = np.array([5,72,13,100])
b = np.array([2,5,10,30])

res = np.add(a,b)

print(res)

[  7  77  23 130]


Subtraction of Arrays

In [3]:
a = np.array([5,72,13,100])
b = np.array([2,5,10,30])

res = np.subtract(a,b)

print(res)

[ 3 67  3 70]


Multiplication of Arrays

In [4]:
a = np.array([5,72,13,100])
b = np.array([2,5,10,30])

res = np.multiply(a,b)

print(res)

[  10  360  130 3000]


Division of Arrays

In [5]:
a = np.array([5,72,13,100])
b = np.array([2,5,10,30])

res = np.divide(a,b)

print(res)

[ 2.5        14.4         1.3         3.33333333]


Exponentiation (Power)

In [6]:
a = np.array([5,72,13,100])
b = np.array([2,5,10,30])

res = np.power(a,b)

print(res)

[                 25          1934917632        137858491849
 1152921504606846976]


Modulus Operation

In [7]:
a = np.array([5,72,13,100])
b = np.array([2,5,10,30])

res = np.mod(a,b)

print(res)

[ 1  2  3 10]
