SUM

In [2]:
import numpy as np

arr = np.array([20,2,0.2,10,4])

print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))

36.2
36
36.2


In [3]:
arr = np.array([
    [14,17,12,33,44],
    [15,6,27,8,19],
    [23,2,54,1,4]
])

print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))

279
23
279.0


In [4]:
arr = np.array([
    [14,17,12,33,44],
    [15,6,27,8,19],
    [23,2,54,1,4]
])

print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=1, keepdims=True))

279
[52 25 93 42 67]
[120  75  84]
[[120]
 [ 75]
 [ 84]]


Mean

In [5]:
arr = [20,2,7,1,34]
res = np.mean(arr)

print(res)

12.8


In [6]:
arr = [[14, 17, 12],
       [15,  6, 27],
       [23,  2, 54]]

print(np.mean(arr))           # entire array
print(np.mean(arr, axis=0))   # column-wise mean
print(np.mean(arr, axis=1))   # row-wise mean

18.88888888888889
[17.33333333  8.33333333 31.        ]
[14.33333333 16.         26.33333333]


In [7]:
arr = [[5, 10, 15],
       [3,  6,  9],
       [8, 16, 24]]

res = np.zeros(3)
np.mean(arr, axis=1, out=res)
print(res)

[10.  6. 16.]


Max dan Min

In [13]:
a = 10
b = 21

print(np.maximum(a,b))

21


In [14]:
a = np.array([2, 8, 125])
b = np.array([3, 3, 15])

print(np.maximum(a, b))

[  3   8 125]


In [15]:
a = 10
b = 21

print(np.minimum(a,b))

10


In [16]:
a = np.array([2, 8, 125])
b = np.array([3, 3, 15])

print(np.minimum(a, b))

[ 2  3 15]
